name: Sync to GitLab

on:
  push:
    # branches: [ main, master ]

jobs:
  sync:
    runs-on: ubuntu-20.04  # <--- Изменено с ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git remote add gitlab https://ce808e69:glpat-PcPNi3HGEnEYP_YCuxQV@gitlab.preax.ru/onboarding/ffb4a937-d67.git
          git push gitlab --all --force
          git push gitlab --tags --force
